[package]
name = "xsd-delphi-code-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.14", features = ["derive"] }
# crossterm = "0.26.1"
quick-xml = "0.29.0"
unicode-segmentation = "1.10.1"
# ratatui = { version = "0.21.0", features = ["all-widgets"] }
