{% macro fixed_size_line(content, size) %}
  {%- set content_length = content | length -%}
  {%- set space_count = size - content_length -%}
  {{ content }}
  {%- if space_count > 0 -%}
  {%- for v in range(end=space_count) -%}
  {{" "}}
  {%- endfor -%}
  {%- endif -%}
{% endmacro fixed_size_line -%}

{% macro build_arg(name, type) %}
  {{name}}: {{type}}
{% endmacro build_arg -%}

{% macro join_args(args) %}
  {% for arg in args %}
  {{ self::build_arg(name=arg.name, type=arg.type) }}
  {% if not loop.last %}
  ,
  {% endif %}
  {% endfor %}
{% endmacro join_args -%}

{%- set timestamp = now() | date(format="%d.%m.%Y %H:%m:%S") -%}
// ========================================================================== //
// Generated by Delphi Code Gen - Mode OpenAPI                                //
// {{ self::fixed_size_line(content="Version: " ~ crate_version, size=74) }} //
// {{ self::fixed_size_line(content="Timestamp: " ~ timestamp, size=74) }} //
//                                                                            //
// {{ self::fixed_size_line(content="Title: " ~ api_title, size=74) }} //
// {{ self::fixed_size_line(content="API Spec Version: " ~ api_spec_version, size=74) }} //
// ========================================================================== //

unit u{{unitPrefix}}ApiClient,
     u{{unitPrefix}}ApiModels;

interface

uses u{{unitPrefix}}ApiClient;

type  
  T{{prefix}}ApiClient = class(TInterfacedObject, I{{prefix}}ApiClient)
    {% for endpoint in endpoints %}
    function {{endpoint.name}}({{self::join_args(args=endpoint.args)}}): {{endpoint.responseType}};
    {% endfor %}
  end;

implementation

{{"{{"}} T{{prefix}}ApiClient {{"}}"}}

{% for endpoint in endpoints %}
function T{{prefix}}ApiClient.{{endpoint.name}}({{self::join_args(args=endpoint.args)}}): {{endpoint.responseType}};
begin
end;
{% endfor %}

end.