{% import "macros.pas" as macros %}

{%- set timestamp = now() | date(format="%d.%m.%Y %H:%m:%S") -%}
// ========================================================================== //
// Generated by Delphi Code Gen - Mode OpenAPI                                //
// {{ macros::fixed_size_line(content="Version: " ~ crate_version, size=74) }} //
// {{ macros::fixed_size_line(content="Timestamp: " ~ timestamp, size=74) }} //
//                                                                            //
// {{ macros::fixed_size_line(content="Title: " ~ api_title, size=74) }} //
// {{ macros::fixed_size_line(content="API Spec Version: " ~ api_spec_version, size=74) }} //
// ========================================================================== //

unit u{{unitPrefix}}ApiClient,
     u{{unitPrefix}}ApiModels;

interface

uses u{{unitPrefix}}ApiClient;

type  
  T{{prefix}}ApiClient = class(TInterfacedObject, I{{prefix}}ApiClient)
    {% for endpoint in endpoints -%}
    {% if endpoint.response_type.name == "none" -%}
    procedure {{endpoint.name}}({{macros::join_args(args=endpoint.args)}});
    {% else -%}
    function {{endpoint.name}}({{macros::join_args(args=endpoint.args)}}): {{ macros::type_name(base_type=endpoint.response_type.name, is_list_type=false, is_reference_type=endpoint.response_type.is_class, is_enum_type=endpoint.response_type.is_enum) }};
    {% endif -%}
    {% endfor %}
  end;

implementation

{ T{{prefix}}ApiClient }

{% for endpoint in endpoints %}
{% if endpoint.response_type.name == "none" -%}
procedure T{{prefix}}ApiClient.{{endpoint.name}}({{macros::join_args(args=endpoint.args)}});
{% else -%}
function T{{prefix}}ApiClient.{{endpoint.name}}({{macros::join_args(args=endpoint.args)}}): {{ macros::type_name(base_type=endpoint.response_type.name, is_list_type=false, is_reference_type=endpoint.response_type.is_class, is_enum_type=endpoint.response_type.is_enum) }};
{% endif -%}
begin
end;
{% endfor %}

end.