{% import "macros.pas" as macros %}

{%- set timestamp = now() | date(format="%d.%m.%Y %H:%m:%S") -%}
// ========================================================================== //
// Generated by Delphi Code Gen - Mode OpenAPI                                //
// {{ macros::fixed_size_line(content="Version: " ~ crate_version, size=74) }} //
// {{ macros::fixed_size_line(content="Timestamp: " ~ timestamp, size=74) }} //
//                                                                            //
// {{ macros::fixed_size_line(content="Title: " ~ api_title, size=74) }} //
// {{ macros::fixed_size_line(content="API Spec Version: " ~ api_spec_version, size=74) }} //
// ========================================================================== //

unit u{{unitPrefix}}ApiClientInterface;

interface

uses u{{unitPrefix}}ApiModels,
     System.SysUtils;

type
  T{{prefix}}ApiException = class(Exception)
  end;

  I{{prefix}}ApiClient = interface
    {% for endpoint in endpoints -%}
    {% if endpoint.response_type.name == "none" -%}
    procedure {{endpoint.name}}({{macros::join_args(args=endpoint.args)}}
      {%- if not endpoint.request_body.name == "none" -%}
      {%- set args_length = endpoint.args | length -%}
      {%- if args_length > 0 -%}{{"; "}}{% endif -%}
      pBody: {{ macros::type_name(base_type=endpoint.request_body.name, is_list_type=false, is_reference_type=endpoint.request_body.is_class, is_enum_type=endpoint.request_body.is_enum) }}
      {%- endif -%});
    {% else -%}
    function {{endpoint.name}}({{macros::join_args(args=endpoint.args)}}
      {%- if not endpoint.request_body.name == "none" -%}
      {%- set args_length = endpoint.args | length -%}
      {%- if args_length > 0 -%}{{"; "}}{% endif -%}
      pBody: {{ macros::type_name(base_type=endpoint.request_body.name, is_list_type=false, is_reference_type=endpoint.request_body.is_class, is_enum_type=endpoint.request_body.is_enum) }}
      {%- endif -%}): {{ macros::type_name(base_type=endpoint.response_type.name, is_list_type=false, is_reference_type=endpoint.response_type.is_class, is_enum_type=endpoint.response_type.is_enum) }};
    {% endif -%}
    {% endfor %}
  end;

implementation

end.