{% macro fixed_size_line(content, size) %}
  {%- set content_length = content | length -%}
  {%- set space_count = size - content_length -%}
  {{ content }}
  {%- for v in range(end=space_count) -%}
  {{" "}}
  {%- endfor -%}
{% endmacro fixed_size_line %}

{% macro build_arg(name, type) %}
  {{name}}: {{type}}
{% endmacro build_arg %}

{% macro join_args(args) %}
  {% for arg in args %}
  {{ self::build_arg(arg.name, arg.type) }}
  {% if not loop.last %}
  ,
  {% endif %}
  {% endfor %}
{% endmacro join_args %}

{%- set timestamp = now() | date(format="%d.%m.%Y %H:%m:%S") -%}
// ========================================================================== //
// Generated by Delphi Code Gen - Mode OpenAPI                                //
// {{ self::fixed_size_line(content="Version: " ~ crate_version, size=74) }} //
// {{ self::fixed_size_line(content="Timestamp: " ~ timestamp, size=74) }} //
// ========================================================================== //

unit u{{unitPrefix}}ApiClientInterface;

interface

uses u{{unitPrefix}}ApiModels,
     System.SysUtils;

type
  T{{prefix}}ApiException = class(Exception)
  end;

  I{{prefix}}ApiClient = interface
    {% for endpoint in endpoints %}
    function {{endpoint.name}}({{self::join_args(endpoint.args)}}): {{endpoint.responseType}};
    {% endfor %}
  end;

implementation

end.